docs:
- any: ['doc/**/*']

mmg:
- any: ['src/RodinExternal/MMG/**/*']

mesh:
- any: ['src/Rodin/Mesh/**/*']

variational:
- any: ['src/Rodin/Variational/**/*']

solver:
- any: ['src/Rodin/Solver/**/*']

utility:
- any: ['src/Rodin/Utility/**/*']

core:
- any: ['src/Rodin/Core/**/*']

alerts:
- any: ['src/Rodin/Alert/**/*']

plotting:
- any: ['src/Rodin/Plot/**/*']
