docs:
- any: ['doc/**/*']

Rodin::MMG:
- any: ['src/RodinExternal/MMG/**/*']

Rodin::Mesh:
- any: ['src/Rodin/Mesh/**/*']

Rodin::Variational:
- any: ['src/Rodin/Variational/**/*']

Rodin::Solver:
- any: ['src/Rodin/Solver/**/*']

Rodin::Utility:
- any: ['src/Rodin/Utility/**/*']

Rodin::Core:
- any: ['src/Rodin/Core/**/*']

Rodin::Alert:
- any: ['src/Rodin/Alert/**/*']

Rodin::Plot:
- any: ['src/Rodin/Plot/**/*']
