[build-system]
requires = [
    "setuptools>=60.6.0",
    "pybind11~=2.10.0",
    "cmake>=3.12",
    "scikit-build>=0.15.0",
    "ninja; platform_system!='Windows'"
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

